# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=200)),
                ('notes', models.CharField(default=b'', max_length=500)),
                ('is_working', models.CharField(default=b'', max_length=10)),
                ('rating', models.IntegerField()),
                ('category', models.CharField(default=b'', max_length=100)),
                ('author', models.CharField(default=b'', max_length=100)),
                ('author_email', models.CharField(default=b'', max_length=100)),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name=b'date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name=b'date modified')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=200)),
                ('notes', models.CharField(default=b'', max_length=500)),
                ('is_working', models.CharField(default=b'', max_length=10)),
                ('rating', models.IntegerField()),
                ('author', models.CharField(default=b'', max_length=100)),
                ('author_email', models.CharField(default=b'', max_length=100)),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name=b'date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name=b'date modified')),
                ('cpu', models.CharField(default=b'', max_length=100)),
                ('motherboard', models.CharField(default=b'', max_length=100)),
                ('hard_drive', models.CharField(default=b'', max_length=100)),
                ('sound', models.CharField(default=b'', max_length=100)),
                ('is_sound_working', models.CharField(default=b'', max_length=10)),
                ('display', models.CharField(default=b'', max_length=100)),
                ('display_configuration', models.CharField(default=b'', max_length=20)),
                ('is_display_working', models.CharField(default=b'', max_length=10)),
                ('graphics_card', models.CharField(default=b'', max_length=100)),
                ('graphics_card_is_working', models.CharField(default=b'', max_length=10)),
            ],
        ),
    ]
