# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='manufacturer',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='does_card_reader_work',
            field=models.CharField(default=b'', max_length=10),
        ),
        migrations.AddField(
            model_name='device',
            name='does_optical_drive_work',
            field=models.CharField(default=b'', max_length=10),
        ),
        migrations.AddField(
            model_name='device',
            name='does_usb2_work',
            field=models.CharField(default=b'', max_length=10),
        ),
        migrations.AddField(
            model_name='device',
            name='does_usb3_work',
            field=models.CharField(default=b'', max_length=10),
        ),
        migrations.AddField(
            model_name='device',
            name='lan_network_chipset',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='wlan_network_chipset',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
