# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20160329_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='haiku_arch',
            field=models.CharField(default=b'', max_length=10),
        ),
        migrations.AddField(
            model_name='component',
            name='haiku_revision',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
