# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 20:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0003_component_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='author_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='component',
            name='author_first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='component',
            name='author_last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='component',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='component',
            name='date_created',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 10, 20, 55, 5, 440090), verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='component',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 10, 20, 55, 13, 885834), verbose_name='date modified'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='component',
            name='is_working',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='component',
            name='notes',
            field=models.CharField(default='', max_length=500),
        ),
    ]
