# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20160403_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='category',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
