# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_device_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='rating',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='rating',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
