# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='component',
            name='author_first_name',
        ),
        migrations.RemoveField(
            model_name='component',
            name='author_last_name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='author_first_name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='author_last_name',
        ),
        migrations.AddField(
            model_name='component',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
