# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_auto_20160110_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='notes',
            field=models.CharField(default='Test Description', max_length=500),
            preserve_default=False,
        ),
    ]
